name: sliding_panel
description: The most customisable bottom sliding panel you can find on pub.dev. Just as you want it!
version: 2.0.0
homepage: https://github.com/GigsEthiopia/sliding_panel

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
